apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: AWSLambda
  description: |
    A service for testing Backstage functionality. For example, we can trigger errors
    on the sample-service, these are sent to AWS Lambda, then we can view them in the 
    Backstage plugin for AWS Lambda.
  annotations:
    aws.com/lambda-function-name: fusionapp1,testcron
    aws.com/lambda-region: us-east-1 
spec:
  type: service
  owner: david@roadie.io
  lifecycle: experimental
